services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql-inventory
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 22022004
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql